apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: sb-instanceid-cassandra
  name: sb-instanceid-cssndr
spec:
  replicas: 3
  selector:
      app: sb-instanceid-cassandra
  template:
    metadata:
      labels:
        app: sb-instanceid-cassandra
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SERVICE
              value: sb-instanceid-cssndr0
              #.local-service-postfix-place-holder
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: http://cassandra-image-place-holder/cassandra-openshift-orchestration
          name: sb-instanceid-cssndr
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-instanceid-cassandra
  name: sb-instanceid-cssndr
spec:
  ports:
  - name: cql
    port: 9042
  - name: thrift
    port: 9160
  selector:
    app: sb-instanceid-cassandra

