apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sb-instanceid-cassandra
  name: sb-instanceid-cassandra
spec:
  containers:
  - args:
    - /run.sh
    resources:
      limits:
        cpu: "0.1"
    image: http://cassandra-image-place-holder/cassandra-openshift-orchestration
    name: sb-instanceid-cassandra
    ports:
    - name: cql
      containerPort: 9042
    - name: thrift
      containerPort: 9160
    volumeMounts:
    - name: data
      mountPath: /cassandra_data
    env:
    - name: MAX_HEAP_SIZE
      value: 512M
    - name: HEAP_NEWSIZE
      value: 100M
    - name: CASSANDRA_SERVICE
      value: sb-instanceid-cassandra
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
    - name: data
      emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-instanceid-cassandra
  name: sb-instanceid-cassandra
spec:
  ports:
    - port: 9042
  selector:
    app: sb-instanceid-cassandra

#---
#
##Route to client
#apiVersion: v1
#kind: Route
#metadata:
#  name: sb-instanceid-cassandra
#spec:
#  host: sb-instanceid-cassandra.endpoint-postfix-place-holder
#  to:
#    kind: Service
#    name: sb-instanceid-cassandra
